# Generated by Django 6.0 on 2025-12-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DR', 'Drones'), ('RB', 'Robots'), ('CM', 'Camera'), ('SP', 'Spare Parts')], default='DR')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=500)),
                ('long_description', models.TextField(default=None)),
                ('price', models.FloatField()),
            ],
        ),
    ]
