# Generated by Django 6.0 on 2026-03-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_available_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='new_image_field', upload_to='media/categories'),
            preserve_default=False,
        ),
    ]
