# Generated by Django 6.0 on 2026-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='heading',
            field=models.TextField(blank=True),
        ),
    ]
